drop table if exists Race cascade
drop sequence if exists hibernate_sequence
drop table if exists Race cascade
drop sequence if exists hibernate_sequence
drop table if exists Race cascade
drop table if exists Team cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Race cascade
drop table if exists Team cascade
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Race cascade
drop table if exists Team cascade
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Race cascade
drop table if exists Team cascade
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Race cascade
drop table if exists Team cascade
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
alter table Member drop constraint FK5nt1mnqvskefwe0nj9yjm4eav
alter table Team drop constraint FK632pjv4vt283ta5hksthha6od
drop table if exists Member cascade
drop table if exists Race cascade
drop table if exists Team cascade
